source "https://rubygems.org"

ruby "3.3.0"

gem "rails", "~> 8.0.3"
gem "sqlite3", ">= 2.1"
gem "puma", ">= 5.0"
gem "bootsnap", require: false
gem "rack-cors"
gem "tzinfo-data", platforms: %i[windows jruby]

# API
gem "grape", "~> 3.1.1"
gem "grape-entity", "~> 1.0"

# OpenAPI docs (local path while gem is not published)
gem "grape_openapi3", path: "../../.."

group :development, :test do
  gem "debug", platforms: %i[mri windows], require: "debug/prelude"
  gem "brakeman", require: false
  gem "pry-rails"
  gem "factory_bot_rails", "~> 6.4"
  gem "faker"
end
